;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-forward-char
        ivy-switch-buffer
        keyboard-escape-quit
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        markdown-outdent-or-delete
        mouse-set-region
        paredit-backslash
        ))
