;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-change
        evil-delete
        evil-delete-char
        evil-find-char
        evil-force-normal-state
        evil-forward-char
        evil-insert
        evil-next-line
        evil-normal-state
        evil-yank
        ivy-switch-buffer
        keyboard-escape-quit
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        end-of-buffer
        evil-backward-char
        evil-mouse-drag-region
        evil-previous-line
        markdown-outdent-or-delete
        mouse-set-region
        paredit-backslash
        ))
