星期日, 2018/4/1


* keep work with jounal (Good for you)
[[https://github.com/howardabrams/dot-files/blob/b2e8a36832d4b9964042aca839f3ff0a3e6724a7/emacs-org.org]]

[[https://github.com/jueqingsizhe66/ranEmacs.d]]

** 23:14 非宁静无以致远                                               :地球:


#+BEGIN_SRC org

  【注意力】是什么？
  是你的心神关心的东西，是你在乎的东西！东西指的是人事！

  注意力是指你心神关心、在乎的唯一一件人事。
  注意力是一个沟通你和作者的一个神秘通道（注意力是唯一一个一个通道
  只能进去不能返回来，只有找到出口才可以）
  （不达目的，别想出来）
  【注意力是一条神秘的单向心神通道】
  保持心态【保持keep going on】
  诸葛亮说：“非宁静无以致远”




#+END_SRC


** 23:26 持续专注[一段时间只做一件事]                            :java:地球:


#+BEGIN_SRC org
  在一个满眼都见得到诱惑的时代里，保持专注，用心做事也是一种修行。有热爱的事物并对其始终保持热忱则是生活的意义。
  由始到终地去做一件自己喜欢的事情，到底是怎样的一种体验?是不忘初心，还是工匠精神?这或许只有真正做到过的人才深有体会吧。
  每座城市，都有那么一群不被关注的人，他们总是用最细致的手法，做出最令人感动的极致细腻。用平和的心境、任劳任怨的劳动心态，经营好小细节、小技术，这就是最为平常的劳动者的姿态，也是“微而著”、“小而实”的劳动之美。执着于一件普通事情的砖匠，是对自己和生活负责的态度;能坚持不懈的专注于一件平凡的事情，自己也就不再平凡。
  想做好一件事，必须得用心、走心，更是急不来【急事缓办】。微不足道的地方，或许就蕴藏着较高的智慧与汗水的积累，把微小的工艺，做精、做美、做到极致!
  专工需匠心，匠心品好专

  来自 <https://www.duanwenxue.com/article/4620171.html> 

  有始有终，持续【keep what?】专注

  微而著，小而实

  集中时空精力进入其中

#+END_SRC


** 23:31 细节的魅力 ：见微知著  小大之理 四两拨千斤              :java:地球:

【关系论】
【本质】 具体的社会生活的内部联系，是外在生活现象的内在逻辑

我相信： 只有经过加工和改造的细节，才能让作品与本质真实有机地联系起来
        【一段时间持续的改造一件事情】
【细节】
细节是缝合本质真实和现象的阵线，是突入本质的向导
细节的选用与剪裁实在是一门学问【select and cut and drop】
【故事之人，细节犹如骨骼之血肉】
【封装java包的细节，达到简便的使用方式】

一、细节之所以重要，在于它是构筑艺术作品真实性的基石
本质真实是艺术真实的核心与灵魂。所谓本质，不是玄妙的“自我意识”或笼统的“时代精神”，而是具体的社会生活的内部联系【关系论】，是外在生活现象的内在逻辑【内在逻辑】。[2]细节就是缝合本质真实与艺术真实之间缝隙的针线，是突入本质的向导。只有经过加工改造的细节，才能让作品与本质真实有机地联系起来。相声演员对于语言的掌握往往令人惊艳，基本上各地方言都能随手拈来，模仿个八九不离十。除了语音，模仿他人行为举止也不在话下。无论是模仿方言还是举止，都需从细微处着手，仔细揣摩平上去入中的发声道理，研究人际交往中的微妙差异，方能实现表演技巧的精深微妙。在文本创作方面，曲艺人也会刻意选取独具典型性的细节，融入作品真实性的打造中来。在马克思看来照搬事实不加选择和提炼，作品同样有可能是不真实的。利用细节来实现曲艺作品的真实性，说起来容易做起来难，细节的选用与剪裁是一门学问。


文艺作品都强调细节，由于曲艺兼具舞台表演与文学创作的双重属性，更由于这种艺术形式要在直面听众时接受群众的检阅，每一个倏然而逝的细节都会直接影响听众的感受，从而对作品产生不可估量的影响，因此，在曲艺创作中无论如何强调细节的重要性都不为过。当然，细节也是作品整体的有机组成部分，离开人物设计、情节编制与舞台表演，再好的细节都只能浮于艺术的表面。如何在一个优秀的整体设计中穿插合适的细节，实现寻常处见功力，细微处见真章，也是值得每个曲艺创作者深究的话题。

每一个开源产品都是一部可看可不看的电影

1. 人物细节
2. 情节编制
3. 舞台表演【场景设计】

 见微知著：
【解释】微：隐约；著：明显。见到事情的苗头，就能知道它的实质和发展趋势。

【出处】《韩非子·说林上》：“圣人见微以知萌，见端以知末，故见象箸而怖，知天下不足也。”汉·袁康《越绝书·越绝德序外传》：“故圣人见微知著，睹始知终。


【管中窥豹】纵然有着一叶障目的感觉，他受了那么重的伤，他会想着怎么翻过来？
怎么筹谋呢？！

想要立足必须要有真本事！！
行动是一切最有利的证据！！


习惯无常，才乃庆幸！！！【生活的态度】
