* 星期三, 2018/5/2

** 23:56 Start with a plan[point form]
Start with a plan - Think about the kind of presence you want: social media, blog, website, etc. 
But don't get hung up on details. Point form, not details

But when it comes time to build that presence, they figure that they need to do everything at once. 
And, predictably, they get overwhelmed

Patience, Patience, Patience……

* What should be turned off while you work?

1. wifi
2. Notifications
3. Mobile Phones
   

{{{
    Writing is much better without the Internet. This is by
    a factor of 10 or more. When you have the Internet at
    your disposal, writing often gets interrupted to go
    check on this or that. But writing with no other good
    options means you're going to really be able to focus.
    - Leo Babauta

}}}


* what you should stay?

1. 25 minutes block[番茄时间]
2. Focus on one task
3. Stay on task even if you finish early
4. Write in Point form
   1. write in sentence fragments
   2. Each fragment is one idea
   3. Flesh out the fragments later
