#+BRAIN_PARENTS: 科研论文


* 基于多项式混沌的不确定CFD模拟方法                                   :crypt:
:PROPERTIES:
:ID:       18507696-c950-4099-8ebe-a1f7645a0a0a
:END:
-----BEGIN PGP MESSAGE-----

hQEMAw7kGOoigxp9AQf+Pjn+4dH/pCmSigDo6S8vT8HBq1BTwFiRBgLo8NoEbmEy
BT+859iejRmzufJn+EGkF7KH3DKx0uSamHhPk/F9zCLKVPIuGcHI/DIefdLDK/Nf
F/JMuMbmvNP+AaahzbzUK1YGvPdaXfsrLmzXVo8PHPWnHoVKYcuN3mq85y7+Kemo
eTPa4Rw5DGvLh7TwnvNEgud04J9Z0t/C0Vyvo3laaN4JjdNJlnLCCStXxk+CslHZ
EGMN0UZ7cskGjz1+PmO99wZY73gMRImA9p8+w7d5NGuXXt9u2DeDQxGoolQp7DWU
XWsNvbVmBZCUuUnvD2M5P4/nM1X4g0rnrcfs8TJohdLpAdumfHCNbjMKEM2Xit22
kk6eLShwn/8Hyv2uUuEP8N5Ml+clfNnWDrzL7Dr+z0F1frhGLDaZtnDbO+mmMGPg
msPt80t12Memrm+XtpHqFFKXC5nI0rrFwPibkaX60xvOSmCWjTkUW3t8c0C7RI+m
sHPjv3E0AM0wCmPcdYOYszcaj23MOI9MzJa6pA+5y2nO0UHq7b+l6MfveUZSoktD
QgFAEV6v9+gesQz6mHi+UdQpdvwjuyYvu7GxD7YQtw9oqYjNcmo7nuAZaAZ0l7A9
EB1IPK286ax+0g6ldv4+s5uyvKM0DoiRfBY4uVUXlrtWLTmvkOw8ogjqS9kZGM0H
0tpUCKcGjBjraagQWNakaMRT0iNz321TdRF7OS1g8sHch2uXA28u8Uz7ncNR+msN
jK+/1gOzTbBSL2LjlvPOxq1L7yHrF8UZ2srB1K+X3NSp4ECYqLEKrC6tIJ6jfeDq
tEmh0vEEkpGE79e0yn6wPwxPieD301jd0cxYVMxIg7WPeZOorh9vzkUUZsmNiXDr
13OoT7fKyWCUQA3DIavPyyuvCkC6ZYicuRMTuHCZw3X3u1fJJ2U8DCSFDJpJ1zx5
9hMGlGhjAg93GmuwnvlFR3a3DTTcaswtOlXXcLGk1HFo4qJpbDe9VhQk/6D7RMxE
7IyCfPqP8trkD9I6Kb/HNustsS/x8oLEWcb2BKJf14+utnGKt8SIiZWbExuuqwR7
trFnMXneUTwph0WQaZ+E
=Yi/l
-----END PGP MESSAGE-----
* 风轮多轴角运动模型                                                  :crypt:
:PROPERTIES:
:ID:       ac7d5c26-d568-47bd-a50d-4bc002a8eb03
:END:
-----BEGIN PGP MESSAGE-----

hQEMAw7kGOoigxp9AQf/Y45Ufv6ebjnWdZmH8dKAB8ZxJbhFpsyPQDWA7jt8nxE1
FWeyihPRHFFyH5HaO/j9loYlG13G/WeiyH6X9fAw2Ja8x8sSOHoQXGHkaxi9YWpj
ilvYRXIz/11KXkGrrOZLo33cQnIErAdHVRHuX3WVrglE4pvdMpNAT3MkbM97OoX+
HndV/erwI31P0xvXnNIbqa1OFLPaURQlSQYHSL+HlKD7QCc9uxeSzWv44ZXHWaVn
KXr4552UD/oegDzo4prjOaAyhqp6eXBbpDfgCDu74SGdENX9FWPoyQSWOMOeQ99s
wac40kC41zQ8JXIygG51jrO7cgfbNXZYPziJ+4Az1tLpAc5QglmcGnVieA3Qzv1q
3CkgVKO4IzMExAMH77todgPxsPg0hwgy86Zh8cjEekTTodICHijMpBmnLAPABVrO
33MwB3JGRhF2CD5pACI8PR2dw+XmME01hQ6Zvm2s00IVu2ZXFiAD3NTVesPNpqnu
ctonzO0K/GHvOU4HNGdm3wA4nxr8t1OxBFFlDx6YbsWaHNqweCw6q+pWzG4sYI3E
l2nls0ZvveC+zMXoNteorw1MEsngqvwzSlnfWwzT3v81XkVFKF26NcdcOWSpibEd
/HgpoYYAAALkjDS3ndNHr2Ro/kVbwDvTxxPiA734P2rZbY+Aza8IvQemOkOdfJcd
7uxTTHRxCxaOCeLg9plIZOF7HlcoGGJ3h5PWyem99pi2NoTnuWXRtT8QaOzDPoZU
1LZ4xCdkfcofMqDmbfXfOxkpYCVu9RRJKI7j5FjHQOn6eDf22uAGFO6on8tOudSZ
xwcAq3i2hCipw094Cgdm9dqni7iceVdxDzEpj3sVClR93bwzMfV/aj/ebmx2Zg9b
ix4gBR7d1l+F2YPSGQE/cSdLs9RNbya6zOsTZceS1vBUtl3oUL9UJzsij16F20vl
hJOmdkKMdn7WnfBXHX+4nrE3tHp4GT6V/z83sQsnDEm8Njc6GLGO83MLQY7h73I5
fGqTvmYeO5TqxIMmRPbmVxRTerUshEGM+HL5Kmz+VPW+CQ7pAEUVhQw+QrglOetT
BhFN112rlV2AowPMMi50SoJUdpn/Ojt3u+nDQACSJ1SO5aGiTsPEXEHPbl9zON2h
oxOma10=
=Maf7
-----END PGP MESSAGE-----

* 大气湍流下风电机组近尾流特性与失谐特性                              :crypt:
:PROPERTIES:
:ID:       0c94b60e-7daf-4ddd-97b4-604dc01b506c
:END:
-----BEGIN PGP MESSAGE-----

hQEMAw7kGOoigxp9AQf7BpbgPj0sVbRVe1G6aMQsoHhFkG7HaJ1g2oqUkmsNUNea
Bu4Y1t3Y1p8V5UjnTKDCtKyDRhfbs0s1xZuAV/GBDMXoaH0BD8vq5nzjFvpJMXlD
D+5KdHTtjprsImDUhCPXeqMG+ZdejRPpNW+sfi2DoRS9nGRvjmSojSClCaJpp3aX
itiLqpKe3iOMnk6NM5B/z8fODVMqPDhQmqRoWP4kO6DkajsO32REGoa1C6fwqoyB
HedYj9j7wZteeb8ATB0IWdEnwAdt5IMSUf5ta0M7he50pL8l8qPACM7xku6fCQ9B
rD4tqgwrYqFd8gTUycOilpz4GLioz1oL4VOgU8H3ztLpAWy0YZC7SlOFxK2vQSJt
Lep48XZWy2ba0aeaNq31zPP+gitA2jw+6/1FrMpITY9hqv9cvybXanRb4ASfZ7br
6VrHTbN0uN8tZWzD7q1sYz77gCkpRmw8IkkOAeaAp9NZbhITLu+RiPtyUYuAoerq
vAAAWkCamGl1SzECbwZ3W2XlpYq1O26fLHUUyU8L3tI6gP1uW7Ir/S0IjrTV/Y6l
mtwC8x6myciSLjwtB3DzSHrF1/bzkE+0bdx6j7xVsG2XxNW3JT2Pco/EjxKsNjDe
ct/E/8Pe0vpWhIkb2we19NUwm0SnBmytPAvyha9ytFsTJy/orXMOMRGHeXPJTaw4
dfDnJ5DQ92y6RgnfKo0WRH0H5Hwj5Xo8f/946biwf5xMEbu/QDciivSB4SaK3Vwk
+4aKM2W1mr9dHRM+XuKXWqGzFpjfBqiLSA9tP4NYOsOgL1uvMlnvjLrzAwSSPGDX
IhS+dBc7jNXivM6RsXRbQqEfhVhsB5pdajyQCfmMUwcZ5STWi2d1pDun2+oWZt9n
nZgFQxx5XX/FWrS+H9R41jelkOiJnehS/YQlGOxTbjAeiXJ2IWRbZcWQLJjrxN3q
kgjiRINS9fpwIdDmux4bhb7T/GHaO19pZakBjAE+BBbvhPOJAxkyteWUsSYscZ/1
X8cATKlUd8BQ/6BjH0LGdNHAN9a6UcH6SvMtDtsFZbosEbUw5XIFJa+zAkTTA+7v
M9PaQpFd/TG7SW6xjhtlKA9gDUiyRSzgWBoMdWqlhzNH+4zXjGcvmtnb9PWgQ4gp
dxJ9wMMmxNgZXasZGgFvxdRgk6U7+0YUWuLdYIf90VJYUiEh2EKjw/WZqpIQbYBZ
GoyRT69tU6jEkY0z/TXmOrmd8TPwBRZAvbffFLFGP4ndRX3Dg7nxln5Rft2sGm/J
nMV/PVIuDIbyjNgw7slDXiy5G+mGyVi8gjdijDIFMTk6UaNl/VuF/4ADTc1XPz7g
8mFdNpTtT44wJa/mxKJADlHobRHaF//8KSk=
=kJ8Q
-----END PGP MESSAGE-----

** 研究内容                                                          :crypt:
:PROPERTIES:
:ID:       9eca7bde-ce1e-4fc5-b752-a9fbeb8833ce
:END:
-----BEGIN PGP MESSAGE-----

hQEMAw7kGOoigxp9AQgA0DyGVQM+oaBrTp1phujZBp4ChnvCO7izPjN4H/B5nClJ
phYqvh7MxK+h9qFJCGMD/tVY0aLv7wnrYW/eYdoiCxFcVap4XQyloVWWpNaEiXhE
5Q9tyHk+bsJAa9Twlep+j0erL9BuWkThPJ2Nh/9COgUSY55vvDyuKni2D9wdQARI
rTi2TfjI26CuJhs8C7fQRAobPFzy1tI37fmWPubxWhKfinW585cPiR2+uNbxMHff
pC573LUp0XkRDRP+XcHsbpuDmrIQWryxxfpWVmiXNwQxLC8ABdxriVzUQf3pPAmt
Nv23et+qvQ0xWDsP7fLcQe0Fe90MqetWvAX4fH8Y1dLpAdNFPJM6+YZqoFFLztl7
lKpD0qVo4DD3AkiQsqRLxVAt7PSXQqHpex/pLy1tdCJ2YEmAwdmOIbPh5RYtNjH1
C32jgfO690cOyAWYJN04z29T4QBAhVrtViGD9WoTMtrprRtYcGs1IFT5jchF28Sa
e1G/c6Yt2nQgdJxSRO8gvQX5GjbCF24h70H1cbaEw99FsSkwWg2VidiytS0bPz7S
o8dCCxphqcrEu387FtH1EoHXzOgd1yw9M2mvXWMA3u0RSJXv9WFf9geJ6ZkgVRvy
hO9q74hvADomXugD/fLSYjb/xwQDVq8mfzYMZ8WxasN8zFQpSoTYbJ49j9qsfoIU
OiKyUb89qQ/GojZ/1XrIRSoEHp4aDJMBvRIzLcJdVidLNhNLOgS/yVy856GYL4OS
xJoDluZGhLr8SlDCiAZFyrVEs517l7MbNbGYG9TpxONnBiM2/w9ZHLVwjQ8D9sWi
lzPlhYcgVZK8x2hCzCAWZwdMig/8puS5tTIVBrBlOLS/xhAORcVYXgbWWNflV21r
JtlHjZzaA3tIVXDlCdhw5YdiC1LqFqFyWUiCZWaCNdmGh8MNvu2sSY5yh088J7WQ
J8brbcjGRES+zK6CYnSdyF173YiDwdeIms94A2PCpWoLdoAHr5Rh14m+FjU72Cc0
oZO6kJkVkYkovMd7DscSY8qUUi+lOX7MPSPjYqBrnruArXKZGYV5vcpT9+6F4A0+
Ay2l/s3MuAfNNvaMftpodwBQmyOg3ht/zFjJJJLmIwyGPgO51jjcNft5Ra1YWNuO
kFK3wDUOW3WZdFg4TsnlbKa4kjd3jkeogguEGQ1pa6X48METo0P3ip4jqgqjo3RQ
NGuR8RbP9zw2iB04MUApnkh44zVg+Q==
=qJCL
-----END PGP MESSAGE-----


** 研究意义                                                          :crypt:
:PROPERTIES:
:ID:       67fbd1e9-8f7b-4261-b7de-2a599012a52f
:END:
-----BEGIN PGP MESSAGE-----

hQEMAw7kGOoigxp9AQgA2YpV9G0kiZ5xCb7w9Oy/wvxLwZA1H31rtiMA2a43/7Yr
GSilAkUcpkyZ1M/eIPjqP3wex4ChBRJT5K3U/xU243R0k4nkp4nt30b7aBeb0TsL
i+TY070QKwd8RRMtgYSbR/RwEiW7F1dM5vvMzzqTCcYewHbP7pJs0RkfrCgbs5+z
nmPaAigyiM9bEL/sO744uFc6fs4rwSbTZIM8uGL7cpAlpWE1IgqWXzRfUEmczkSv
IKiIEhtZsS2m15kjqRCK8rfzL7r9KhviZp7nR496YrVoFj9wpk32aBiDPCry1R9I
ZjsoyV4o//vN+kKK9naivcVWzGwiubw/S73+CZWJ8dLsAZveNMgpL4dFngQttpes
9vece7hTFez93ugv4K31ySaKQx84vQODeHWvJa1KdAgdf6qTyAqLUX/k8N1hl/Kj
3lyGXk/Td/TroRjO/C9w4731Itkoyg0ZE6xLL41tHAT3pMX5ymALNgfzg9eWFfOH
acMZ5ajje1Q3vfY00d7BycCX6fnoqLKtrptJy/Iii/IxhCAbcs3aROYaFle9Dsqu
BwnjvjA0eGyZo+M7NPRh4gd69T7ROPj79ECfJmgOwMfSv1OeBaSAH1D/fsdTJang
dPP9fuqiOjqd/r/5VcOuBakneALMBixyg4gATPe+23d8uFEKYG7ABc54eFCdiWp5
nOrkVHz9PrQa1/aDHRTwQGD3VCNHdg3QmryQZ7s9N0cisvQh7ZEaEiFVHgfrzizZ
kBe9j+88UBYg3FAbMYl/uURQD+bM/ORlIiyJ3K9E/nKtfWk1sVS8UdNbkbJPm2sj
rCaV4Cvm0RvC8X3S8g24cj68xJwrKelmBhxDBW/0oxrvHf5jJMW8TJYKXwnXES1E
0moTlRRAae9FyjH5hgVb7R7yfVBqXhHeZV1RpmON3iJWovYLmmJw8ZOnQsULDL5R
pINkPUL9o9UZGc6R31DJD6TFRPoymIY5V/y9WTq/f5QCvbQCWZYxyYRrf8NoNpiR
1rC3SUdyogvq8Hvx5XVZRbjPkk5cPew3Asgbg4UseFxwFQ58/76OAlPhpFBPg39i
CTjzOsC1EfOUi1oVA8TcqVZ6cAAzRX7DMUf54Ta7I9U+jYkkOpRqeU3qrbTSLBf9
G7kCd1E4F9L4OTOh+/l73XipyHDrySISIK9w/HH/SpixyfwDUVCXbNeVseyTjL2J
IGPyryh7U79pcw+h1WP1cqR8MVDWPrcYMq/9VWGfCFa1oVLSZ/ETL8a5neAhrzWv
RsuK6Bo+pktr+9Zn69MqrM6qvtH8eiAQ0dr6Vz7IqrtbZsN67LHVQ6R14HsKyZVA
PhtfV2fFQIeFy4yrc+CNN4VqT/a7aarztugKkCDyI0k+gIoJTOY0Cx/G6l35L0AM
u/dxoCRZ8NZXlPGl+xl3auFLF1Go6cGjm4ll4tlb7IwUE8vyfqUSlbWiM5xDcRlI
7gsI0Z0HqaXJQ3KQ6SqVbFNN4RwxNJGjzrB4a9W3Sp89uiBETvO8pd2KeYojm4rk
4NPoQ3b3i7R0lhqqBbFNEdhxDmiNFdo3Z/qsTgbH6jCr7cK3tPHJolx5OjrrTcqc
3NSTzWCF15kohHkYg333I0DEo8ZTA/2qqegq1GsGHixOC/+tAbN7gedDMMiK5raf
PDIfRNh6CkTkYSwBZzCVVadEb0eelsEkeZDQccUy8djIzcNPM6KhdeISYhP1L1/8
L/0gO9LDEZ2Yzmb3SSmJO1oLiXCOVA6on+MXzUN1lJZPZ3OnKc/HQyuYV5/l6Fed
jdwjyomb7if+fKylqm/0XZyz04jK5YAmBaQ3+0NX/Vh3GJAjiNLH1aW2hiqpzVrP
/Ee5Gq7ltL8/9IuBrhadDTwe+WIYO1EIVjANO15R1EsR7R1ESb8lhm0FxEYRWFHX
oeohnIihig0aCSPZzFW1Wkks59A+D+EMUYxCkCA+nqt9r9euXMbfMgnVVx6n/f8Z
ig+7M0YjFJr7gITK+zzjj7CYpeIYMqAHZG+q4JITsazVhIUzMABiJiENxF9GUa5N
prXIT32TwTsgAN00p4AnaYYgKlZjOiZiCsyltB7JrBfJ3dch1DSzL0Nfzi6DRX9p
2j6XoZVSRRNK/GHGvQlR9oReOQx3pjGTT46Jn9pCnsud4ht72jRnHUBohMdgqUNe
PRLC6uHfbBqCIdXiBg2tmnV3atkoFK5yK97X5trcbC/9t0ICmMMUoVrbTAPIqx4Z
+fX9mXb/lnWJ1V5S+OtBNLCqzGbxbSZwrEyKRvkxg2XjVYLdboaq2dghEDGiTzoj
d0m+VekJ+vHUztQrDTzvhZQeVkr3WfQyEX1fHz5+vA7FGabb1fY+Ns272C3qJkVb
dsZfsLB/+cpzcWlx+mdGH0bEfWvuGYDl0jmGXxT0DxsIVGaRKEOO7md4oYkfUmhU
NlHCnG8MWi8SYQuyyGmJvnvmIayQ1wfMMDaVi+W7gk/KFU6Ekj0imR5UkMaVhQmr
+0pIiuN5AF0/OIPQX0RgZABMgcrq7TeMDK/TTDavwW75j+qukkDo1p5gHVZ20Gs1
kcZ09yBqkGnz91NeBr2Npujn+bGM8D6Slr7zfx//DPBdM8YzSUwBttrbk91lVqSu
Oi43pTIAVfoqX8Gkw5QuTopa0yUy2uiUfy3Jr1TwYdn27efnZtBGCVJ77nnmnt71
Vdxm0evqiRGdnpUPL5+XsPb3SGMwaTVzkrQDhUKz0Fyd9nV8HloaN/4WM2Uahf+g
DBOu+sbmEU1bPsEYexqB7ElmE1/lXllqv+fS/oa9jadYEbAvnHuR+7EjX0doc7Ca
8gcj3XUmGDcVbn3L7j/IgwwYACUIIjqOqZKf3IuihaGjV2n8gZTinkhMYYyizLqk
ie8ZfFEXsH/tmM5FPVFfx6knH6pLZn6OYSYYDb3A1W8R8KCWMpBAun0kkSY5fz+i
JnWtX3qJyznPbGvN9eLWyaZWokpflflUfae1sPWMvOur1u7q7UFXVtwLQVECe+2O
dNkpj+kBG5R8MpL/mfQkyrMPp5x9L1V7kHci85/MMZIZPdBp435O7gi6vmohTNzy
iUIaJ0kkwpyZRNHhVky78zM+RHGapnczkV+3mRV12ouE9vz2d0EGOPpnK3tMVq1G
LyFQt3ia32AR9+4S1d3fnNpLKXQM1UN/DepfUFloSgI76Dajj/JzEVSNy3hA9ms0
agQDYJnHo9iB2HBEnjmJ8/aYz2UHowTMooGCzO1cXPCtazCLgRTGyIxjunGkFAVq
6jS1zUqGvx1RUI6BIux8Zb0vHhXu7OOyllYmVi4PeDgVZQ2sXyruDq0RNvwuoMpe
vE5Xu824a2MAsSvR3+SnSrnNWgqs7QB4+l1Uj/aTvpG45JFsZccPON3RHTeB3VjR
5or06bnmwIz/XPOfmMPV8BJdcmIbh3N1zeahiBWyoRj3TJCdQsXy1Xw04qUnzg0b
786ZXER/V8HjhycWf1sLXm74M6nLuCqtnwqowjxrDI64A1kzA+WjIFM1MVV6mhT0
IqcEk+LGC3akuZ091rpUGbTLfntGvNAf26p2jVSYTssT8vSSwxoL2hG6zsriWQxL
35TpQbmqLfSYogMtEDny3UZcp3jZ+diJ1FEv3+8nhPdmeTwKen8YiMOcMXIaiEG+
vus1QqQlHyrTY+WFL8A2rvtO2jG5Bej/kP8J3mvqMHF5Br2BSFnbdrPSYU8cUsSe
gcaWhEiZzwKdWJ8I5YlpsjA0A0FL2xZHJ3wAsbGBgDBUNbRShcFeqboKNeXz/A5V
E4yonyVgzjSRGKCRA7EpipnHd7R0j13evaNLfmxL7HL1Qh0mnqfkbzgxqf39/rRk
kypRlEQ7RP+rVL3PGfFLByB6xGM5t/XlPeQA1nM53uPJFe/QRCwbGEWjSS1kMFI0
I+YGVAK7cbmfwafTZTCF5qNyogeyqg+qpVsMcwxf0ZzF3nfxvIUAkjRf7F/NZAda
8JZQBWIJcoqMuQpGkYvp+aKEJocZYMj9axSWRumGuwisDWaKVdy9ZJfKuZ3lqP8d
3RCs9bNQ5x+MoMdByy1N4zDb3n0WReoQ0pfhc+vM5Q50L/22oHhJ3R5Nf/k8FdDI
SvuBSIBUjl0HE6BdUPmU9e64jW+MaLqPBWxIpnm+mbM4DjUy7icNzlIwjFsPeEVB
ThSCj3WENbhHcoeeKW96iyYTWOLoZ061cLrsOfG8VRGynIzuutrIi+HOA/arz1gv
2b7VqKUslys2BDV4vs8wbi3fwkVg/1QOlCMxWBf6Fyo3kudHJBxCRgJF1bhDwteB
nafI/Zxsdh8ME4L2Jzjg9/nI9q+Zs2WT3BntyfUVvz40BPAB1HC7rn2b2nm7zqn7
uSSKdrj1Euthw9rDqFvbIECuIRo8PHoNwF5jO3WYWErfe9UE7ehZYho4YaO5bApP
dLF+yaqVpYP25M3at1FUJVvupK+cRVwwhQOUht+zYhTeFyg8YC0dzNsb5kR7ZWrx
z7TKqnZK1plj38Qr4ZD1pPcMtPNNGY3xEep23FZZEzbbuxC2fTUSsS/woSZYG+7O
EuKVxQqQmV5s6kN7UGDTYIVj7lGhHm7FbIpk3uP5RiXP/5B/i30dLFc7uv6GX4zJ
2/Bb/em076ipo281jQOVjxxiyTVzdi8+wbZkth5MM9JzA7jrZq8UddNykxeIuE5a
vowYltaPl0sQ/kzHdcTrdx+RCV2GRfr2KY0gI2L2Gt9kaAVMkX2vMa1LibK5ZeI3
zcZ4FciZlcEC/2QseNLTQRWGnavZqqqXxxS945KVX1gLd8ilL+b59D5CGoWsZwby
cn0MejgTrzhPPjxDLnuVcZFYR/YqUQ4q2CUOnELWs2kcmUrtiTpb+f0c79OsUDJs
KUmqtuDIifaPoBD6XWzVebwG2VEBWblTAEaa03z4Psaw0GLbk5PC3Laeyon3Skhl
esIKYuzFAVjdCVDCJHMqvuINzwWDS9f7lvUYj8narJx5hUKlF798O5h8/zrv3LE9
ewMjPscTWY43HZ3SzD4/qFzIAcCG4/SnmKiiKXz5RBzp9HehuzBYHKJkZ19kXpkg
Ukn8yflcmOBaxDksIl47zioJf1Luw8YyM06pdoS9ffLka1NkvQ9SF8zt6zwT6Fep
bHIWwTxtD/5YhepT0PMFnei3WtyFtp039gSRW892D0vYAkjtwmzxC07XQ5Wqug8Y
8ru4QttCj/vxpkM6Jh5HNkW2zRO6ZyzyGqxv8Sizk37dGOmG0ySGN0k9PNpEUEwC
v309Zr01nD6D2NuaQyAHvZIr+UOmnQi2RniiAuBVEtrZB4sqxZBo3DvU1IaA0xgH
U4L2xiG5t1HpHkMsj9Be34fhK5q+YJZjCmWQ/OGuY+7+L3/Fo8ApUToeG/zgCtkH
ANdNJKWeAslrwlgy1CuIqR/6RoFwainwY/HOVWGu3Mt0c5+WoyM4W3Zvm0zBhvSi
S7xtY6mZlapBcNxMElVF8xAs5X7C5tgT5tWdbHUUWMCjjsUYnBykS0G4SZY8N4/8
llDnLCgTnPaHfnwFCQwhZ6FzD4qtZ7mPr9SgHta4n0OoCfUas2GFF6XMvnFaeQ3j
pHWq/8m7WdxafZFsLEGI1C4DC34wQxMpQKrdPk6qVWZfpC269mODVwLG1jmR1gII
07VlMDxf02kU47ust5T4D2shEd2spCZZ/HfiHbFIRu1ft9S8e2fheCuu5taQSqbc
+1PRDbwemvVfYMqzVHdnvNXWkWYH/kQAx/LQ/Yr4DJSdLzc9Amn6ncYKGGAYZvb/
Gse2qvCmXLatqfkHx7/OFbzbqcbXfJ9P9UMZceOJnMPv4cTRqr8TfbXkn/lEuGjl
kepQT8Is0pQjbqjs2RuProEqBYVpq7RsazupXAMDLbLxG0eQeOoSDaBaXRaeb7X7
tETehfbfnSduqLOacjLPywpDNpZU0zcmwrokI62XT2qEKnxGOF6DFfuoPNySvVV7
CgLGHFEhg36f5td/Sywg5BC7157dXQ2fIchyl5GzqVOPECuNy0n/adq0CF6wku/b
agA04X4I3hqH2syiafYXOxXZ69iD98KTJmc9L72E+sJsMT20H/e4uU53n7x+PrQ0
ctOVlu4w7OghmFVhxU+VG3WC4EcQevsCB5JROo2zg8vKZ0krG1wPh+f4dpte336S
zbGVc1r2iQl33FpOf0pEfqsfmqnqlNEoOpifnbWUmD4w10i7olqP2IJZ6J4Wjulc
IGEse1fzWSppPCl43e7QXBnxWOlgZcXTWzp7QT52OBHPmaZHqNlNpshaXwJ/iaI6
jxT4/V7tiz7+cIq1pmeiOCZi4zcT80NNaR458BRPO8WuUYIXgAM4ECO49BYEyOgn
EIIhb+jckkeixWY9wNOPXyCx5Lo/M0/Hc1/eXjXEALl0QEePppuVDqQSuIHHlBI2
EUdvZwQPFHyfgsniFKHGFMUCipDASuHfL4ABejbqEVHTyruEF7ykmkMsLNf4R+Fa
Sy6PGYv0kzyua5PFgbqwG0sCC1vsaESTyAoh1UqRlHczFYspAhHhCBTaYYIVLWcn
FP9twyMNqVc5jk1Tzu297e0aG05v9zHHNx8EnV9lViPkWyOXw5YBCiMxBNFas+aC
hX18g9UJvyDuycB4STB+bKR5V+ehVzEMnG+X1FByee6z4Z/GZ1KRw+u7PBLAGnXu
MnDWjvGgsk8ekPB8f/WqX3SgDgS7hfI4kyhHhltLbBL9vMGxSRGxvhmYg/pwbDin
9qOrumWfI+td8m3enzPHNoRTWt2FpN+mlRnrXQxOI0brudY0I2ZbF2nmJFSWlKRn
SwQbunoZjN/7s+CZtD/kYIjsNwmx7MzI+q25O1hZR6gYZSXFb93ORdHOce//02lp
6HWsHTE5t5AngrGWv6/iMl6o7wCHK8bDOcvO0+qKEVI3J1a9EuPI8LycRv852DhQ
VhX8mzh3GvNCVaBbqwfstVGzTqGOVVcntL/BGIF/n67m3tZ5UGCbCegOKgxbUbR9
CwVHsNHve/VpevVgmXkLBCilsV80n3NEVvSbZYT2NxgyIby5UrQp8P57DRMyrVvE
dSMx+nXUQ6wrCi6xagteTZKqjhrS9+Nuw1QrxuaIqbEj4wiYQcBS7Ysxf11zMy3x
ol0Xm5CxTf3gE1TeXn24vcbhJvOR27TwaWkM4g5iXCWzIkSaHAERPVoku1VeXwm8
N/H6G2CAj/e1FP2PONbos8sZwDvjacb36NnoD2ItYfUATipmeuQV0E4D2qM0D8mJ
mrsIF+PVgZaqmYJuJjDMeLaNKEIJPOO5MBVEkHTA6XuBFQnrOF/+/MH9qQW8iwW1
BDkJPYBsHSKixNixEOfLNGH6F0yQDjTzbkXGE7SQR0hMfPn+v5ajfxJrEx5q/N/n
nbNrHDormuHCzRAot7lBHIN81qyYAj2ddoaME93v6uS92JeXOT0BildfcvM3NvWD
kchYZMsEgbc8iKul9eqKILqJgdBJbNX17Dv4MYJuOt9+wx7BHMQ1uM9TGYXnD76g
GCHhZ9cKqqoXTHxClbbnPti5ffIHKt49K6IJtRe4QQ==
=Z+Qr
-----END PGP MESSAGE-----

** 研究价值                                                          :crypt:
:PROPERTIES:
:ID:       872f9f35-0213-4d6f-8214-bcc9d006176d
:END:
-----BEGIN PGP MESSAGE-----

hQEMAw7kGOoigxp9AQgA1BywndUKIrpILv5sg5QQbTI2ya1WsaHUjXX6Ko0VN9Ix
dRB8i2pJ08XbmhG2byECnlZRGNV/BnxPJEjZMqZKahR3Uh/955vtK2JVbOILdnhC
j5ZCZ6ZQeJ7FYnGbhMLaAYYIQLzL+fdxfRhGdqqNwdjQ0uADE8pk40laOR2O3dgv
JYNzjOHzT/vZEmgD7RXsBh5wIVOfQo33/fCZ/hRflqDzBV0CwHpOHGuJ49abKS8D
NvHgCNR5+SA2cjT7y14m3bvKjDDvEnNLA5u5sJq7HQM2d5G37Ole7VPzGQB8RoUt
XN8vRn+N8ShgPEW1fM1phalI1p1zkX3lyFzRrabJ5tLqAWR3UnVa52wZONXwQ/zQ
JhUEMOh5oDggmGRA8WzT2qCtmbRu/Ea+XGMqk0ssrjA/C3SUZFgLBlfK/B/x5+tS
VSPPSnWpNiXxs+haKTc2ALfkjfC3YruThDZcmFMs/SnQbk2YZ96Nr1SSoOMDyb38
nGslCIc2NbXqwwwvKQcGsqCX02vGxusGIlaIqBbAk44hQzjw8ZXAlv1uvqWxVNH+
m0CDDp9DWKZ0sfiIkQWD2wXzve9KNQr/fiVEGFRSu0vdJsiZybLDKWBbax94ktsz
PRPSd3dEKZAUbl/wjIM7DFWaCk8kS5ESfBR0+qJ9DSRILGm6/8tjclFy9kBfuZ0s
Um2Hy8SsA683EgU257j47Vz6tXJkT2shyL3T4mHdzraNZ5KVtX5u24lEhXe+KZZJ
pv0qvyiCMbRUYBjAmtp9IlHSvhTWULz7i/lJZ31nrPpwY2nC+LBjnHYgyWffwT49
DYZzZvwSb8fQHi5r44cDEA/GQNdDuAHghlpZnJlgHBEcgXy24WWsA6TJ3kpBOF95
uyiUZpn+YwIk2YA5db3xnO6hx6HeZnI1soj/kJ1LRGatxMQNHQeR0wdlFi4lxAiE
oCVRYfugkxiedMTtAJrukYxlfyYtwTLYDxmt/FzY97LmGOGLpM3jnFZUKLd/wChK
kDM0VpyOI+Yq8rRRQ/3w2iwL/XgxDIS2p3V3LxjYaVuB8Qir547XKgPbj1+ZbgAf
RmNRB2WIoZnrESOT1DHXeT1i8D8KDvxDHxo4g9ZXQKpppQYXmAkRpVqyXUOvgu/3
I/+dhEe9XGJiGv3OJxdCyphIKyloJ6BX1fKyBMrFPTxFur0G0AvdrtJbiaoItUnG
mHwMxnSkk8ZXar2sMwyp1nvRWARGJp4FFM4ro/02uKegyB2kSrzVz3KDLmGoROad
i8Xmd5BItJw7mkvWO/+TkmcIOPtTk71g3Q1JGnm4I6u45jjFUeHVmPXU3IbEZjkn
upz7htzR2S5pU9Xv1sjUAvtcg5ot/zavR3yivJRNYWmcNS39Bk7yP5eJy7rWLf2v
CMA8ZZ5gedYoHYA2jMHhIas+2eMhi3ksBGlGIHP09AAWeg6QdAMNpFYgS4DqQwH5
qowr4Bo2eiUyDkL8j1nnlG2sHx4gTUSBHJOI1S/VJ1mK76YJC/5PF2dXlNnTPYZC
MbYTiDKsdkg+KWyn3E3BFPLYwlwLP3hxxvaR0G08xUlEJaH3+n5UrczyiEGxWgTF
r2Zn7VxXIJi64H2SvM4bPQBQtsSeI3MIAJFLi18XGST8Oxq9+bGIKODDZk5tf1SP
PST73gi5JdXm/h89kbTbqVGWGK7hAYI3BuYywIhO/7kzz6bsPlZ4CABClSsoBFqI
z8EKiSuVz7jxvej2qqcmgz0D4Ph9YSx8ZZE+uhRN6r40/Uo7QtxmOqlqOhAwCFaJ
ZFTH5S+kJweDzvfExX6XXosSyYm/nCcY+ojvtR8AJG+mWh+X0idq6nCuTy6nrn/m
V5irw8Za65JAqtZzKE1s07lectmQq/No/WuRm+GwV+w1za6p4NCZF5xGru3kQDth
fvV8C7dV2y2y2AQYaKuTvYKXvTe/iHBgA1RoFqn6mECR21YVO6f8nDN8Q1UOc4ZT
99sMj1fJbKWHwIEWU5dGn7posbmYGolQuKn8PeVAFxeQZtnL3777UnKbT+8G+/m1
LseRedUzN9Tuirng9mN4xKVaVLvOVNikQjHIAmfM2Z0bPqsiSqJ4ysB0Z2Eq5+fZ
2tiGhZyacmlQsYoG1Pz6BwIBowLjfz/Iif+JSQDfS7tsKZsxEIEgLSHis/nRUaQU
N3uKFsH9k1X6F2s6b30kl9cHldhlWcdTf+Ew/shjtxocxvSCxspEC6zj4AtXjJPg
Ia+hV3czN2ZD9sh8k9e9piWARoS1uSCZS2vw2SUo/+gQtby1due2sCoH/vrvSa/R
nMh9kS/iGlJx0Hvx2M4JakpXYMs6bCcHZqK2ZTY=
=DzTo
-----END PGP MESSAGE-----
* 非定常
:PROPERTIES:
:ID:       611eaefe-b59f-4234-aa05-b21f14ab61ca
:END:

** 4.湍流非定常
:PROPERTIES:
:ID:       5e51cb35-e761-4c4f-af85-51f656933632
:END:

一般只能通过DNS LES进行研究了
** 3.分离引起的旋涡脱落非定常
:PROPERTIES:
:ID:       3b0da20f-5e2f-411e-87c7-67f871ea493a
:END:
** 2. 风向非定常
:PROPERTIES:
:ID:       6912cff2-d850-4a71-b03d-f4b41714b06d
:END:
** 1.相位非定常
:PROPERTIES:
:ID:       c0d36639-36f7-4635-9a6d-e17719cb5361
:END:
* Information Source
:PROPERTIES:
:ID:       2c5202d1-5d63-4f1a-910a-332784694e15
:END:

** Discoverability
:PROPERTIES:
:ID:       8ee4f990-e46f-4d12-90c2-2636c6cc2ddb
:END:

Five fundamental psychological concepts for discoverability:(from the book <The Design of Everyday Things>)

1. affordances
2. signifiers
3. constraints
4. mappings
5. feedback
* Be critical
:PROPERTIES:
:ID:       0c6de2f3-3388-4ff9-99e8-0f541ff86125
:BRAIN_PARENTS: 科研论文
:END:
:RESOURCES:
:END:

** understand the topic from different perspectives
:PROPERTIES:
:ID:       df167cb1-8ed7-4270-b546-1737f6e26dcf
:END:

*** read the related texts
:PROPERTIES:
:ID:       9ea4d76d-e72e-47c6-9a48-c4ebb0aeed70
:END:

    The point of making up the story is now to concentrate on how all your bits fit together;
 what you want to end up saying, how your work supports that conclusion, how the literature 
relates to the argument you are now putting forward. It doesn't have to be a true story of 
why you did that: but a self-critical and measured account of what you know think can be said about it.
    
1. how all your bits fit together; 
2. what you want to end up saying, 
3. how your work supports that conclusion, 
4. how the literature relates to the argument you are now putting forward.


**** framework
:PROPERTIES:
:ID:       ad6c8a91-bfa5-4612-8f05-294820e01e9e
:END:
**** approaches
:PROPERTIES:
:ID:       28dca5c9-b7f1-408a-80dc-c0d973f2379b
:END:
**** theories
:PROPERTIES:
:ID:       82cb2e87-02e7-4d76-b488-2c520ea8f04d
:END:
** present your evaluation and judgement of the text
:PROPERTIES:
:ID:       5b58677b-4fc8-431d-a5c9-203a7a7ca77f
:END:
*** Set Goals?
:PROPERTIES:
:ID:       8d842945-8257-4dd1-90a6-f09c2ce04f8e
:END:

What is a goal?

Goal is a start of a plan, plan something to be perform and then perceive.

Goal is like an application, an package , an tree, an house, an set etc.

"""
    For each goal, one has to ask, “Why is that the goal?”
Why was I reading? I was trying to prepare a meal using a new
recipe, so I needed to reread it before I started. Reading was thus
a subgoal. But cooking was itself a subgoal. 
I was cooking in order to eat, which had the goal of satisfying my hunger.
So the hierarchy of goals is roughly: satisfy hunger; eat; cook; read cookbook;
get more light. This is called a root cause analysis: asking
“Why?” until the ultimate, fundamental cause of the activity is
reached.


Goal driven behavior(GHB)
"""
**** Bridge of Evaluation
:PROPERTIES:
:ID:       fa49732e-b505-4b69-8227-11b3a4432e55
:END:
***** 6Compare
:PROPERTIES:
:ID:       e5151600-e698-41b9-bf4e-4db60ebfc2bf
:END:
Compare the outcome with the goal!!!! This is very important!
***** 4Perceive
:PROPERTIES:
:ID:       40f472f1-9bad-4153-b22d-8ad7fd374f1e
:END:

The state of the world by your investigation and watch
***** 5Interpret
:PROPERTIES:
:ID:       5699fce7-7282-49e1-9845-c9487e379f60
:END:
Intercept your perception , using your knowledge
**** Bridge of Execution
:PROPERTIES:
:ID:       a370a0c1-5aae-4821-b375-f153a268bd31
:END:
***** 3Perform
:PROPERTIES:
:ID:       11b0d241-f98d-4504-a560-df99a2163d92
:END:
Perform the action sequence
***** 2Specify
:PROPERTIES:
:ID:       4d367759-1580-4d94-8309-0e77e320ffa4
:END:
Specify an action sequence(First to do what, how well? Standard, Second to do^-^)
***** 1Plan
:PROPERTIES:
:ID:       4aa2fb26-ab22-4c5a-b39d-a58878401456
:END:

Plan the action
*** Analysis
:PROPERTIES:
:ID:       0666a863-95e7-49f3-b63c-619dd1a08839
:END:
Analysing requires separating the content and concepts of a text into their main components
and then understanding how these interrelate, connect and possible influence each other
**** influence
:PROPERTIES:
:ID:       cff9d8b5-a138-4cc4-ba94-98eea2303032
:END:
**** connect
:PROPERTIES:
:ID:       42917213-2caa-411c-8c65-6fb8564a1c35
:END:
**** interrelate
:PROPERTIES:
:ID:       6290b53c-7bd3-4afd-8492-5242a60167da
:END:
*** Structure:why it is structured the way it is
:PROPERTIES:
:ID:       bb36eea5-df92-4327-b0d8-5d93aa12a201
:END:
 
Planning and expressing the structure
There are really four stages here: 
1. collecting material for the essay,
2. deciding what your main message and argument really are,
3. deciding what structure to adopt in order to communicate that, and
4. indicating your structure to the reader. 

a. The first is the result of the issues and activities discussed above (e.g. selecting, reading, and thinking),
b. the middle two are about "planning" your writing and perhaps writing an essay plan,
c. the last about making sure your plan is clear to the reader. 

{{{
Writing is for yourself, while rewriting is for your reader
}}}
*** the intended audience
:PROPERTIES:
:ID:       1289f198-1543-4dc3-bc12-aec6363e7648
:END:
*** purpose of text
:PROPERTIES:
:ID:       8ef83cf5-6b5a-4469-8c11-f79b22d66440
:END:

    Generally, the purpose of a review is 
1. to analyze critically a segment of a published body of knowledge through summary,
2. classification, and
3. comparison of prior research studies, reviews of literature, and theoretical articles.

****  Value
1. Deciding what your argument is?(60s filter method)

    Thus you will probably at this point have a collection of points and facts you think of some value:
 the raw material for the essay; not a plan, but the elements to fit into the plan.
 Some students will now realise they have too much material to fit within the size limit.
 They must decide what is important to include, and what to leave out.
 The way to do that selection is to do what everyone must do anyway:
       decide what the overall point or conclusion is, what are the points 
or evidence that most directly and strongly support those conclusions,and so on.
When you know what the main point or points are, then you can decide what is most important for supporting those conclusions. 
If this is proving difficult for you, one technique I find useful in my own writing is to put away my notes,
and try to speak a 60 second version. For example grab a friend, preferably one who doesn't know about your 
topic and isn't all that interested, and tell them what your essay is going to say. You automatically make it 
brief to keep their attention, and mention only the most important things without the details. When you hear 
yourself give the summary, that tells you what for you is the most important point; and hence how to organise your essay.
 E.g.
    "My CR is about autism, and the main feature of this field is all the different theories that don't really fit together,
    yet all of them seem to have some support." If you hear yourself say that, then you probably want an essay with one section
    for each of the major different theories, and a concluding discussion pointing out how they conflict. Or you might have 
    found yourself saying "My CR is on autism, and although there are various theories, I'm just concentrating on the claim 
    that it comes from a specific neurophysiological deficit. There's a few papers on this, and I'm going to focus on how strong
    the evidence they present really is. There are really two classes of problem here: firstly the evidence for the deficit is
    scanty and might be questioned at least until more studies are done, and secondly it is hard to see how all the symptoms and
    consequences can really be the effect of a single deficit when they vary so much from case to case." 

Here the essay might take each of a few selected papers in turn, and apply the basic criticisms repeatedly to each. 

**** Body
:PROPERTIES:
:ID:       392e8092-4a85-4f72-8314-2c7565f43a8c
:END:

1. Group research studies and other types of literature 
    (reviews, theoretical articles, case studies, etc.) according to common denominators 
    such as qualitative versus quantitative approaches, conclusions of authors, specific 
    purpose or objective, chronology, etc. 
2. Summarize individual studies or articles with as much or as little detail as each merits
    according to its comparative importance in the literature, remembering that space (length) 
    denotes significance. 
3. Provide the reader with strong "umbrella" sentences at beginnings of paragraphs, "signposts" 
    throughout, and brief "so what" summary sentences at intermediate points in the review to
    aid in understanding comparisons and analyses. 

    So What????? 有什么用处?

**** Introduction
:PROPERTIES:
:ID:       ffb20933-9c63-4f12-8e9a-9351b5f078d4
:END:
1. Briefly expain the topic of the text.
2. Present the aim of the text and summarise the main finding or key argument.
3. Conclude the introduction with a brief statement of your evaluation of the text

In the introduction, you should:

1. define or identify the general topic, issue, or area of concern,
   thus providing an appropriate context for reviewing the literature. 
2. Point out overall trends in what has been published about the topic;
   or conflicts in theory, methodology, evidence, and conclusions; 
   or gaps in research and scholarship;
   or a single problem
   or new perspective of immediate interest. 
3. Establish the writer's reason (point of view) for reviewing the literature;
   explain the criteria to be used in analyzing and comparing literature and
   the organization of the review (sequence); and, when necessary,
   state why certain literature is or is not included (scope). 


**** Summary
:PROPERTIES:
:ID:       2d578b3d-d5b2-4abb-9c53-5c1fb7d9d9d7
:END:
1. present a summary of the key points along with a limited number of example.
2. briefly explain the purpose/intentions throughout the text
3. briefly describe how the text is organised.
4. The summary should only make up about a third of the critical review

    Summarising and paraphrasing are essential skills for academic writing and in particular, 
the critical review. 
***** Summarise
:PROPERTIES:
:ID:       3dfbcdac-54f8-4b96-970b-e3ac98b9c83a
:END:
    To summarise means to reduce a text to its main points and its most important ideas.
 The length of your summary for a critical review should only be about one quarter to one third (1/3)
of the whole critical review. The best way to summarise is to:

1. Scan the text.
    Look for information that can be deduced from the introduction, conclusion and the title
    and headings. What do these tell you about the main points of the article? 
2. Locate the topic sentences and highlight the main points as you read. 
3. Reread the text and make separate notes of the main points. 
  Examples and evidence do not need to be included at this stage. Usually they are used selectively in your critique.
***** Paraphrasing 
:PROPERTIES:
:ID:       2e27370d-0692-43ce-a1ca-c9b7c92c6fac
:END:
    Paraphrasing means putting it into your own words. 
Paraphrasing offers an alternative to using direct quotations in your summary (and the critique) 
and can be an efficient way to integrate your summary notes.  The best way to paraphrase is to:

1. Review your summary notes 
2. Rewrite them in your own words and in complete sentences 
3. Use reporting verbs and phrases (eg; The author describes…, Smith argues that …). 
4. If you include unique or specialist phrases from the text, use quotation marks.




**** Conclusions
:PROPERTIES:
:ID:       3f4111ec-6453-4b54-a314-77b2b089ab6f
:END:
 1. This is usually a very short paragraph.
 2. Restate your overall opinion of the text. 
 3. Briefly present recommendations. 
 4.If necessary some further qualification or explanation of your judgement can be included.
 This can help your critique sound fair and reasonable. 
    

1. Summarize major contributions of significant studies and articles to the body of knowledge 
    under review, maintaining the focus established in the introduction. 
2. Evaluate the current "state of the art" for the body of knowledge reviewed, pointing out major 
    methodological flaws or gaps in research, inconsistencies in theory and findings, and areas or
    issues pertinent to future study. 
3. Conclude by providing some insight into the relationship between the central topic of the literature
    review and a larger area of study such as a discipline, a scientific endeavor, or a profession. 



*** content of text
:PROPERTIES:
:ID:       383a7ff4-fcf1-44da-a57e-6a4582b27d5e
:END:
** question the information and opionions in the text
:PROPERTIES:
:ID:       f44d336e-7952-401c-97b6-6f1686d3cbf8
:END:
*** Weakness?
:PROPERTIES:
:ID:       7d8328e1-b93e-45fb-a000-441ea7ca79c6
:END:

What is your weakness point in your argument?(Strongness) Add it!

reReason(重新推理)

Value- Verify--Valid

Add some evidences to your weakness! Three evidences are enough

*** science?
:PROPERTIES:
:ID:       4a81b658-a9fc-4277-9a42-ce9908aa0a0e
:END:

What is science ?

    More generally, what you are doing in constructing your argument is demonstrating "critical thought" 
(which is often stated as a requirement in the paperwork for PhD exams). It is true that a defining 
characteristic of science is that things are published ("facts") which others then interpret in different 
ways from the original author. This is crucial to the way work cumulates (builds on what went before):
things do not depend on what the first observer thought. And certainly one valuable thing you do in your 
thesis is report facts or observations, or what you did. 
    However a PhD that only reported facts, what was done, measurements taken, would be unlikely to pass.
You are expected to discuss what may and may not reasonably be concluded from your work, and the arguments
for and against your conclusions. Although what you present is in effect in the form of an argument,
you will not mainly be judged on whether or not you persuade others (as you might be in marketing, and politics).
But you are expected to help others decide how much to believe your conclusions by providing them with your 
considered judgement and the important issues and evidence for and against. In discussing not only evidence for, 
but evidence against, alternative theories, and obvious objections, you are helping the reader form their own judgement,
and simultaneously showing you have a good and thoughtful grasp of the issues involved in your work.
 Even if some people don't value your conclusions, they will value this discussion.
 
In a word:
    Science can be questioned and skeptical based on the same facts and different interpretation.

1.    report your facts
2.    report your observations(observations talent)
3.    report what you did(what's your argument)

*** critique(question the value of the text)                         :学术:
:PROPERTIES:
:ID:       d6a2ab3f-b6da-46e1-b2bf-7d4d5a5e2b9e
:END:

    Value means why you are going to do the first task.(Value first, layout second, content later, decorate finally) VfLsClDf
    
    Value why?(背景 和 main idea or main argument---Your argument)
    layout How?(it is a structure)
    content what?
    decorate grammer,style,spell,pageNum,lineNum etc.
    
    You won't know what your argument is untill you have finished the research.

Write things up for yourself, and separately(later) for others(real beneficiaary of your writing is you)
--------------in a word: first write for yourself, then later rewrite for the reader.

    When writing for yourself, you don't have to explain background or motivation, just focus on the facts and
above all on the argument. When that is straight you can later go back and put in what it needs to make sense
to an outsider.(In many ways, all the "glue" and structure is helping the reader to those things.(也就是说原型是
无结构可研，真正内在的东西无形，而之所以化为有形的结构和框架只是为了帮助读者, 所以writing也可以变成painting或者其他任何方式
存在的表达，比如雕刻，比如音乐，比如舞蹈等)

Glue sentence 要注意区分过滤出来！！！(但是其实最重要的是你在心中已经勾勒出了你的writing,你的argument)
```
    The main techniques for helping the reader decide if they have arrived at the right place are titles,
 and "glue" sentences at the start and/or the end of every bit. For example "This chapter described my second and third experiments,
 concluded X and Y, and discussed the degree to which these conclusions can be relied on.
 X is used in the next chapter to motivate the fourth study, and Y is important in the overall conclusions in chapter 9."


```

    The critique should be a balanced discussion and evaluation of the strengths, weakness and notable features of the text. 
Remember to base your discussion on specific criteria. 
Good reviews also include other sources to support your evaluation (remember to reference). 
    
    You can choose how to sequence your critique. Here are some examples to get you started:
Most important to least important conclusions you make about the text. 
  
1. If your critique is more positive than negative, then present the negative points first and the positive last. 
2. If your critique is more negative than positive, then present the positive points first and the negative last. 
3.If there are both strengths and weakness for each criterion you use, you need to decide overall what your judgement is.

    For example, you may want to comment on a key idea in the text and have both positive and negative comments.
 You could begin by stating what is good about the idea and then concede and explain how it is limited in some way.
 While this example shows a mixed evaluation, overall you are probably being more negative than positive. 

    You can also include recommendations for how the text can be improved in terms of ideas, research approach;
 theories or frameworks used can also be included in the critique section. 



* 中尺度
:PROPERTIES:
:ID:       5e50693e-352f-4b69-a406-124efaf0b3a2
:END:

** 风场模拟
:PROPERTIES:
:ID:       9ce98d14-4e17-4d35-9e0c-4486fa64e642
:END:

*** Openfoam
:PROPERTIES:
:ID:       037f9175-6fa6-4f6c-a61d-f1fe1296d56d
:END:
** 风资源
:PROPERTIES:
:ID:       d716c932-5359-41df-9805-c7603e87e74f
:END:
** 可研报告
:PROPERTIES:
:ID:       f6db4bb3-e84c-4a6d-bbb8-ebbc83f318fe
:END:
* lidar
:PROPERTIES:
:ID:       fd652cf7-3106-4815-a916-34983561c290
:END:
* 闪电
:PROPERTIES:
:ID:       fdbacd74-979f-4324-a5f9-f8180ce5319f
:END:
* 噪声
:PROPERTIES:
:ID:       dc6d07e9-cca9-4dea-b5d8-88ea6c64dfe8
:END:
* 气弹
:PROPERTIES:
:ID:       99fd01f9-76a5-4878-a06a-f4b09e801a03
:END:
* 尾迹
:PROPERTIES:
:ID:       6b8a5e03-ef76-41c1-990f-a2598a5e3033
:END:
* 气动
:PROPERTIES:
:ID:       49820ca3-c343-4c50-a890-6d2ba964f5f5
:END:
