* Abstract
:LOGBOOK:
CLOCK: [2018-09-21 周五 14:33]--[2018-09-21 周五 15:17] =>  0:44
:END:

Physically, The flow-field around a rotating horizontal wind turbine is significantly influenced by the existence of wind
shear, turbulence, gust and yaw motion of the nacelle. For a yawing wind turbine, flow characteristics become more complex
than those of a fixed yaw wind turbine, the additional effect of the wind contribution which is basiccally transmitted to the
rotor due to the nacelle motion needs to be considered. Therefore, the accurate prediction of unsteady aerodynamic
load which is calculated by many conventional numerical approaches is still questionable for an yawing wind turbine. 
In this study, the unsteady computational fluid dynamics(CFD) simulations based on the sliding mesh technique 
were applied for analyzing the yawing motion of the wind turbine due to the nacelle motion. The yawing motion 
of the rotating turbine blades due to the nacelle motion is considered to investigate the effects of vortex-wake-blade 
interaction for the aerodynamic performance . The work first validated the employed computational fluid dynamics(CFD) method
with the fixed yaw and yawing of NREL PhaseVI wind turbine. Then focus the investigation into the flow-field analysis of the large
utility-scale wind turbine.  It is shown that the unsteday aerodynamic loads of the yawing wind turbine become
more sensitively changed due to the varition of yaw angle. 


Keywords: unsteady, yawing, aerodynamic performance, flow-field analysis

We used two different turbine models to assess how the size of the  turbine rotor
affects the farm efficiency and effectiveness of the control starategy. T
* Introduction

* Results and Discussion

* Conclusion


