#+OPTIONS: num:nil toc:nil
#+REVEAL_TRANS: Convex 
#+REVEAL_THEME: Moon
#+Title: Slides by ox-reveal and reveal.js
#+Author: Ye Zhaoliang
#+Email: zhaoturkkey@163.com 


#+ATTR_REVEAL: :frag (grow shrink roll-in fade-out none) :frag_idx (4 3 2 1 -)

* I will grow.
* I will shrink.
* I rolled in.
** hellf
** dsdfsdf
** sdfsadg
*** dsfsd
*** dfsdf
*** gasd
*** sgsd
* I will fade out.
* I don't fragment.



#+ATTR_REVEAL: :frag (appear)
* I appear.
* I appear.
* I appear.

** Advance

#+BEGIN_NOTES
My notes
#+END_NOTES


很有意思的


#+BEGIN_SRC org
  ,#+BEGIN_NOTES

  演讲者模式
  使用s，进入演讲者模式，类似ppt

  ,#+END_NOTES
#+END_SRC

In interview with Magnar Sveen, he gives some good advice in learning Emacs:

1. Learn Emacs on its own. Don't try to "learn Emacs and Clojure" for instance. I would suggest learn new tools before you have to use it.
2. Grab a friend who already knows it. I would suggest that if you don't have that, at least learn it with a friend who is also learning it.
3. Everyone has their own way of learning something new, so whether you make flash cards, graphical notes, or whatever, use what you know works for you.
Unless Sacha Chua got you first, let me know if I can help.

* image
:PROPERTIES:
:reveal_background: ./spacemacs.jpg
:reveal_background_size: 800px
:reveal_background_trans: slide
:END:

* mathJax

${n! \over k!(n-k)!} = {n \choose k}$

